name: CI - Testes da API

on:
  push:
    branches: [ "main", "v2" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependˆncias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-train.txt ]; then pip install -r requirements-train.txt; fi
          pip install pytest

      - name: Rodar testes
        run: pytest -q
